env:
  global:
    - CC_TEST_REPORTER_ID=75c7ab4b9e49fab27658bfd004735721b927850b1b0f3168de9077d7f51102b3

language: python
matrix:
  include:
  - name: "3.5 Tests"
    python: "3.5"
script: coverage run -m pytest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install -r requirements-testing.txt
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT