env:
  global:
    - CC_TEST_REPORTER_ID=75c7ab4b9e49fab27658bfd004735721b927850b1b0f3168de9077d7f51102b3

language: python
matrix:
  include:
  - name: "3.5 Tests"
    python: "3.5"

install:
  - pip install ".[testing]"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: coverage run --source core --omit */site-packages/* -m pytest

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
